<a href="https://colab.research.google.com/github/methrex/MAP6385/blob/master/homework/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**2.2**

Computer problem 6

---

In [0]:
import numpy as np

#initialize two double precision and two single precision arrays
x64 = np.array([2.718281828, -3.141592654, 1.414213562, 0.5772156649, 0.3010299957])
y64 = np.array([1486.2497, 878366.9879, -22.37492, 4773714.647, 0.000185049])
x32 = x64.astype(np.float32)
y32 = y64.astype(np.float32)
xy32 = np.multiply(x32,y32)
xy64 = np.multiply(x64,y64)

n = len(x64)
ans32 = []
ans64 = []

(a) Forward order $\sum\limits_{i=1}^n x_iy_i$

In [0]:
sum32=0;sum64=0.0
for i in range(n):
  sum32 = sum32 + x32[i]*y32[i]
  sum64 = sum64 + x64[i]*y64[i]
ans32.append(sum32)
ans64.append(sum64)

(b) Reverse order $\sum\limits_{i=n}^1 x_iy_i$

In [0]:
sum32=0;sum64=0.0
for i in range(n-1,-1,-1):
  sum32 = sum32 + x32[i]*y32[i]
  sum64 = sum64 + x64[i]*y64[i]
sum = np.array([sum32,sum64])
ans32.append(sum32)
ans64.append(sum64)

(c) Largest-to-smallest

In [0]:
sum32=0;sum64=0.0
minus32 = xy32[xy32<0]
minus64 = xy64[xy64<0]
plus32  = xy32[xy32>=0]
plus64  = xy64[xy64>=0]
#sort
plus32  = np.sort(plus32) ;plus32  = plus32[::-1]
plus64  = np.sort(plus64) ;plus64  = plus64[::-1]
minus32 = np.sort(minus32)
minus64 = np.sort(minus64)
for i in plus32:
  sum32 = sum32 + i
for j in plus64: 
  sum64 = sum64 + j
for i in minus32:
  sum32 = sum32 + i
for j in minus64:
  sum64 = sum64 + j
ans32.append(sum32)
ans64.append(sum64)

(d) Smallest-to-largest

In [0]:
sum32=0;sum64=0.0
minus32 = xy32[xy32<0]
minus64 = xy64[xy64<0]
plus32  = xy32[xy32>=0]
plus64  = xy64[xy64>=0]
#sort
plus32  = np.sort(plus32) 
plus64  = np.sort(plus64) 
minus32 = np.sort(minus32);minus32 = minus32[::-1]
minus64 = np.sort(minus64);minus64 = minus64[::-1]
for i in minus32:
  sum32 = sum32 + i
for j in minus64:
  sum64 = sum64 + j
for i in plus32:
  sum32 = sum32 + i
for j in plus64: 
  sum64 = sum64 + j
ans32.append(sum32)
ans64.append(sum64)

Comparing these all:

In [1089]:
k=1
for i,j in zip(ans32,ans64):
  print('Method '+str(k)+'  Single: '+str(i)+'   Double: '+str(j),end='\n\n')
  k = k +1
print("The 'correct' value is 1.006571*10**-9")
print("Numpy dot product: ")
print("Single: ", np.dot(x32,y32)," Double: ", np.dot(x64,y64))

Method 1  Single: -0.3472038161853561   Double: 1.0251881368296672e-10

Method 2  Single: -0.3472038162872195   Double: -1.5643308870494366e-10

Method 3  Single: -0.3472038162872195   Double: 1.4068746168049984e-12

Method 4  Single: -0.3472038162872195   Double: 0.0

The 'correct' value is 1.006571*10**-9
Numpy dot product: 
Single:  -0.34720382  Double:  1.0251881368296672e-10


Single precision results have no variation where the numbers are meaningful (8 decimal places in this case?). The value is, however, much too high when compared to the *correct* answer. The default double precision values vary, but are much closer to the *correct* value. The doubles for the first three methods are at most 3 orders of magnitude off when compared to the 8 orders of magnitude for our float32 values. 

I suppose the single precision values are this incorrect due to rounding errors. They can't accurately store all of the information provided in some of the numbers, like 878366.9879. 

Our answers are on the order of $10^{-10}$, but our initial numbers were all at least $10^{-4}$. Even with double precision, we might not have the ability to accurately store all of the digits when performing operations on numbers whose orders of magnitude are very different. This might cause certain operations to no longer be associative, resulting in different answers for different orders of operations. 

---
---


4.1

---
---

Problem 3

---


**Prove that each of the elementary operations can be undone by an operation of the same type.**


*Row swap*

---

Let operations of the type $(R_k \leftrightarrow R_i)$ be operations that interchange the rows $R_K$ and $R_i$ of some matrix. Suppose we have

$(R_i \leftrightarrow R_k)(R_i \leftrightarrow R_k)A$

We can write the matrix $A$ as a column vector of rows
$$A=  \begin{bmatrix}
        \vdots \\ 
        R_k \\ 
        R_i \\ 
        \vdots 
      \end{bmatrix} 
$$
Then, it is easy to see that 
\begin{align*}
(R_i \leftrightarrow R_k)(R_i \leftrightarrow R_k)A &= (R_i \leftrightarrow R_k)(R_i \leftrightarrow R_k) 
      \begin{bmatrix}
        \vdots \\ 
        R_k \\ 
        R_i \\ 
        \vdots 
      \end{bmatrix} 
\\
&=(R_i \leftrightarrow R_k) 
      \begin{bmatrix}
        \vdots \\ 
        R_i \\ 
        R_k \\ 
        \vdots 
      \end{bmatrix} 
\\
&= \begin{bmatrix}
      \vdots \\ 
      R_k \\ 
      R_i \\ 
      \vdots 
    \end{bmatrix} 
\end{align*}
Using the associativity of matrix multiplication:
$$
(R_i \leftrightarrow R_k)(R_i \leftrightarrow R_k)A = A 
\implies
(R_i \leftrightarrow R_k)(R_i \leftrightarrow R_k) = I
$$

assuming we can represent these operations as matrices. So, we've reached the conclusion that, for any indices $i$ and $k$ of the matrix A, any row interchange operation $(R_i \leftrightarrow R_k)$ is its own inverse. $\quad\square$

*Multiplication of a row by a nonzero scalar*

---

I'll use similar notation as above. Let $(cR_k)$ be a matrix operator that multiplies the $k^{th}$ row of a matrix by some $c\in\rm I\!R$ such that $c\neq0$. Then,

\begin{align*}
  (c^{-1}R_k)(cR_k)A &= (c^{-1}R_k)(cR_k)
      \begin{bmatrix}
        \vdots \\ 
        R_k \\  
        \vdots 
      \end{bmatrix} 
      \\
      &=(c^{-1}R_k)
      \begin{bmatrix}
        \vdots \\ 
        cR_k \\  
        \vdots 
      \end{bmatrix} 
      \\
      &=
      \begin{bmatrix}
        \vdots \\ 
        R_k \\  
        \vdots 
      \end{bmatrix} 
      \\
      \therefore\quad\quad\quad\quad (c^{-1}R_k)(cR_k) &= I
\end{align*}

The multiplication of some row by a nonzero scalar can be undone my mutliplying the resulting row with that scalar's multiplicative inverse. $\square$

*Adding a multiple of a row to another*

---

Let $(R_k:=R_k+cR_i)$ define an operation that adds the $i^{th}$ row of A multiplied by $c(\neq0)$ to the $k^{th}$ row of A. It follows that

\begin{align*}
  (R_k:=R_k-cR_i)(R_k:=R_k+cR_i)A &= (R_k:=R_k-cR_i)
  \begin{bmatrix}
      \vdots \\ 
      R_k + cR_i \\  
      R_i \\
      \vdots 
  \end{bmatrix}
  \\
  &= 
  \begin{bmatrix}
     \vdots \\ 
     R_k + cR_i - cR_i\\  
     R_i \\
     \vdots 
  \end{bmatrix}
  =
  \begin{bmatrix}
     \vdots \\ 
     R_k\\  
     R_i \\
     \vdots 
  \end{bmatrix}
  \\
  \therefore \quad (R_k:=R_k-cR_i)(R_k:=R_k+cR_i) &= I
\end{align*}

Adding a multiple of the $i^{th}$ row of a matrix to the $k^{th}$ row can be undone by subtracting the $i^{th}$ row from the resulting $k^{th}$ row.                     $\quad\square$


---

Problem 13

---

**Let $D$ be a matrix in partitioned form:**

$$
D=
\begin{bmatrix}
  A & B \\
  C & I
\end{bmatrix}
$$

**Prove that if $A-BC$ is nonsingular, then so is $D$.**

Suppose we have a matrix $D$ as defined above and that it is nonsingular. Then, we can write 

\begin{align*}
  DD^{-1}&=I
  \\
  \begin{bmatrix}
    A & B \\
    C & I
  \end{bmatrix}
  \begin{bmatrix}
    X & Y \\
    Z & W
  \end{bmatrix}
  &= 
  \begin{bmatrix}
    I & 0 \\
    0 & I
  \end{bmatrix}
\end{align*}

We get the following matrix equations:

\begin{align*}
   AX + BZ &= I \\
   CX + Z &= 0  \\
   AY + BW &= 0 \\
   CY + W &= I  \\
\end{align*}

It is immediately obvious that $\boxed{Z=-CW}$. Using this result on the first equation:

\begin{align*}
  AX + B(-CX) &= I \\
  AX - BCX &= I    \\
  (A-BC)X &= I     \\
\end{align*}

$$  \boxed{X=(A-BC)^{-1}} $$

Using the third and fourth equations together:

\begin{align*}
  AY + BW &= 0     \\
  AY + B(I-CY) &=0 \\
  AY + B - BCY &=0 \\
  (A-BC)Y + B &=0  \\
  (A-BC)Y &= -B    \\
\end{align*}

$$\boxed{Y=-(A-BC)^{-1}B}$$

Using this on the fourth equation:

\begin{align*}
  CY + W &= I \\
  W&= I-CY    \\
\end{align*}

$$\boxed{ W=I + C(A-BC)^{-1}B}$$

For $D$ to be invertible, we only require $A-BC$ to be nonsingular.$\quad\square$

---

Problem 16

---

**For what values of $a$ is this matrix positive definite?**

$$ 
A= 
\begin{bmatrix}
  1 & a & a \\
  a & 1 & a \\
  a & a & 1 \\
\end{bmatrix}
$$

If $A$ is positive definite, real, and symmetric, the its eigenvalues are all greater than 0 and real. Let's take a look at the characteristic polynomial:

\begin{gather*}
  |A-\lambda I| = 0 
  \\\\
  \begin{vmatrix}
    1-\lambda & a & a \\
    a & 1-\lambda & a \\
    a & a & 1-\lambda \\
  \end{vmatrix}
  = 0
  \\\\
  (1-\lambda)\bigg((1-\lambda)^2-a^2 \bigg) -a\bigg(a(1-\lambda)
  -a^2\bigg) + a \bigg(a^2-a(1-\lambda)\bigg) =0
\end{gather*}

Which simplifies to 


\begin{align*}
  -&\lambda^3 + &3 &\lambda^2 + &(3a^2 - 3)&\lambda + 
  &2a^3-3a^2 + 1& =0
  \\
  a&\lambda^3 + &b&\lambda^2 + &c&\lambda + &d& =0
\end{align*}

The roots $\lambda_1,\lambda_2,\lambda_3$, of a third degree polynomial of this form satisfy:

\begin{align*}
  \lambda_1 + \lambda_2 + \lambda_3 &&=&& -\frac{b}{c} 
  &&=&& \frac{1}{1-a^2}
  \\
  \lambda_1\lambda2 + \lambda_2\lambda_3 + \lambda_3\lambda_1 
  &&=&&\frac{c}{a} &&=&& 3(1-a^2)
  \\
  \lambda_1\lambda_2\lambda_3 &&=&& -\frac{d}{a} &&=&& 2a^3 -3a^2 +1
\end{align*}

The first constraint is also the trace.

$$Tr(A) = 1+1+1=3=\lambda_1+\lambda_2+\lambda_3 = \frac{1}{1-a^2}$$ 

This gives us the condition $\boxed{a^2=\frac{2}{3}}$

The third constraint tells us 

\begin{align*}
  2a^3 -3a^2 + 1 &> 0
  \\
  2a^3+1 &> 3a^2 = 2.
  \\
  a^3 &> 1/2
\end{align*}
$$  \boxed{a > (1/2)^{\frac{1}{3}}>0}$$

We see that 

$$
\bigg(a=\pm\sqrt{2/3}\bigg) land \bigg(a>0 \bigg)
\implies \boxed{\boxed{a=\sqrt{2/3}}}\quad\quad\quad\square
$$

---
---

Section 4.2

---
---

Problem 1

---

**(a)  Show that if $U$ is upper triangular and invertible, then $U^{-1}$ is upper triangular**

Let $P(n)$ be the proposition that an invertible upper triangular *n x n* matrix $U$ has an inverse that is also upper triangular.

***Base case: *** n=2 

(a *1 x 1* matrix is already upper triangular and invertible if it is not 0)

Suppose  

$$
U = 
  \begin{bmatrix} 
    u_{11} & u_{12} \\
    0 & u_{22} 
  \end{bmatrix}
  \in \rm I\!R^{2x2}
$$

Then, if its inverse exists,
$$
U^{-1} = \frac{1}{u_{11}u_{22}}
  \begin{bmatrix}
    u_{22} & -u_{12} \\ 
    0 & u_{11}
  \end{bmatrix}
$$
which is also upper triangular. So, $P(2)$ is true.


***Inductive step:*** arbitrary $k\in\!Z$ such that $k>= 2$

Assume the proposition $P(k)$ is true for a *k x k* matrix $U_k.$ That is, it is an upper triangular invertible matrix whose inverse is also upper triangular. We can then form the matrix

$$ U_{k+1} = 
  \begin{bmatrix}
    U_k & \vec{u} \\
    \big(\vec{0}\big)^T & u'
  \end{bmatrix}  
\in\rm I\!R^\text{(n+1) x (n+1)}$$

which is also upper triangular. $\vec{u}$ is some column vector of length $k$ and $\big(\vec{0}\big)^T$ is the zero vector of the same size. u' is some nonzero real scalar. Since $U_k$ is nonsingular and since u' is nonzero, then the determinant of $U_{k+1}$ is also nonzero by the properties of block matrices. Therefore, $U_{k+1}^{-1}$ exists, but what is it? 

$$
U_{k+1}^{-1} \equiv
\begin{bmatrix}
  V_k               & \vec{v} \\
  \big(\vec{w}\big) & 1
\end{bmatrix}
$$

where $\vec{v}$ and $\vec{w}$ are both  *k x 1* column vectors, and $v'$ is some scalar. $V_k$ is some *k x k* matrix.

\begin{align*}
  \overbrace{
    \begin{bmatrix}
      U_k & \vec{u} \\
      \big(\vec{0}\big)^T & u'
    \end{bmatrix}
  }^{U_{k+1}}
  \underbrace{
    \begin{bmatrix}
      V_k & \vec{v} \\
      \big(\vec{w}\big)^T & v'
    \end{bmatrix}
  }_{U_{k+1}^{-1}}
  &&=&&
  \underbrace{
    \begin{bmatrix}
      V_k & \vec{v} \\
      \big(\vec{w}\big)^T & v'
    \end{bmatrix} 
  }_{U_{k+1}^{-1}}
  \overbrace{
    \begin{bmatrix}
      U_k & \vec{u} \\
      \big(\vec{0}\big)^T & u'
    \end{bmatrix} 
  }^{U_{k+1}}
  &&=&&
  \underbrace{
    \begin{bmatrix}
      I_k & \vec{0} \\
      \vec{0}^T & 1
    \end{bmatrix}
  }_{I_{k+1}}
\end{align*}

From matrix multiplication, it follows that $$U_kV_k = V_kU_k = I_k$$
Therefore, $\boxed{V_k = U_k^{-1}}$, which is upper diagonal based on the assumption in our inductive step. More matrix multiplication tells us that
$$
(I_{2,1} )= 0 = \big(\vec{0}\big)^T U_k^{-1} + u'\big(\vec{w}\big)^T
$$

Because $u'\neq0$, we have that $\boxed{\vec{w}=0}$. We must take $v'$ to be nonzero if we are to ensure the invertibility of $U_{k+1}^{-1}$. We have determined that

$$ U_{k+1}^{-1} = 
\begin{bmatrix}
  U_k^{-1} & \vec{v} \\
  \big(\vec{0}\big) & v'
\end{bmatrix},\quad v'\neq0
$$

which is an upper triangular matrix. We have shown that $P(2)$ is true and that $P(k)\implies P(k+1)$ for arbitrary $ k\in\mathbb{Z}$. By mathematical induction, our proposition $P(n)$ is true $\,\forall\, n \in \mathbb{Z}$ such that $n\geq2. \quad\quad\square$




**(b)  Show that the inverse of a unit lower triangular matrix is unit lower triangular**

We will proceed in a similar fashion. Let $P(n)$ be the proposition that an *n x n* unit lower triangular matrix L has an inverse that is also unit lower triangular.

(a *1 x 1* unit lower triangular matrix is the scalar $1$, which is its own multiplicative inverse)

***Base case:*** n=2 

$L_2 = \begin{bmatrix} 1 & 0 \\ a & 1 \end{bmatrix} \quad\implies\quad L_2^{-1} = \begin{bmatrix} 1 & 0 \\ -a & 1 \end{bmatrix}$, which is also unit lower triangular.

***Inductive step:*** arbitrary $k\in\!Z$ such that $k>= 2$

Assume the proposition $P(k)$ is true for a *k x k* matrix L_k. We construct the matrix 

$$
L_{k+1} = 
\begin{bmatrix} 
  L_k                 & \vec(0) \\ 
  \big(\vec{l}\big)^T & 1
\end{bmatrix}
$$
By properties of block matrices, $|L_{k+1}|\neq0$. Therefore, $L_{k+1}^{-1}$ exists and we can construct it. Let 

$$
L_{k+1}^{-1} \equiv
\begin{bmatrix}
  \Gamma_k                 & \vec{\gamma} \\
  \big(\vec{\delta}\big)^T & l'
\end{bmatrix}
$$

$\Gamma_k$ is some *k x k* matrix, $\vec{\gamma}$ and $\vec{\delta}$ are some *k x 1* vectors, and $l'$ is some scalar. Just as above, we can then form the product

$$
L_{k+1}L_{k+1}^{-1} = L_{k+1}^{-1}L_{k+1} = I_{k+1}
\\
\begin{bmatrix}
    L_k                 & \vec(0) \\ 
    \big(\vec{l}\big)^T & 1
\end{bmatrix}
\begin{bmatrix}
  \Gamma_k                 & \vec{\gamma} \\
  \big(\vec{\delta}\big)^T & l'
\end{bmatrix}
=
\begin{bmatrix}
  \Gamma_k                 & \vec{\gamma} \\
  \big(\vec{\delta}\big)^T & l'
\end{bmatrix}
\begin{bmatrix}
    L_k                 & \vec(0) \\ 
    \big(\vec{l}\big)^T & 1
\end{bmatrix}
=
\begin{bmatrix}
  I_k & \vec{0} \\
  \vec{0} ^T  & 1
\end{bmatrix}
$$
Looking at the elements of $I_{k+1}$:
$$
(I_{k+1})_{1,2} = \vec{0} = \Gamma_k \big(\vec{0}\big)^T + \vec{\gamma} \implies \boxed{\vec{\gamma} = \vec{0}}
\\
(I_{k+_1})_{2,2} = \vec{l}^T \vec{0} + l' = 1 \implies \boxed{l'=1}
$$

$L_{k+1}$ then has the form 

$$
\begin{bmatrix}
  \Gamma_k      & \vec(0) \\ 
  \vec{\delta}^T & 1
\end{bmatrix}
$$

Because $L_k$ is unit lower triangular, $L_{k+1}$ is also unit lower triangular. We have shown that the base case $P(2)$ is true and that $P(k)\implies P(k+1)$ for arbitrary $k\in\!Z$. By mathematical induction, the proposition $P(n)$ is true $\forall n\in\!Z$ such that $n \geq2\quad\square$


**(c) Show that the product of two upper (lower) triangular matrices is upper (lower) triangular.**

Similar approach. Let $P(n)$ be the proposition that the product of two *n x n* upper (lower) triangular matrices is upper (lower) triangular.

***Base case:*** n=2

Suppose 
\begin{align*}
U_2=\begin{bmatrix} a & b \\ 0 & d \end{bmatrix},\quad
V_2=\begin{bmatrix} e & f \\ 0 & h \end{bmatrix}
\rightarrow&&
U_2V_2 &= \begin {bmatrix} ae & af + bh \\ 0 & dh \end{bmatrix} 
\\
L_2 = \begin{bmatrix} a & 0 \\ c & d \end{bmatrix},\quad
\Gamma_2=\begin{bmatrix} e & 0 \\ g & h \end{bmatrix}
\rightarrow&&
L_2\Gamma_2 &=\begin{bmatrix}  ae & 0 \\ ce + dg & dh \end{bmatrix}
\end{align*}

where $a,d,e,\text{ and  }h$ are nonzero. So, we see that $P(2)$ is true. 

Next, assume that the proposition $P(k)$ is true for some arbitrary positive integer $k$.

Let $U_k,V_k$ be upper triangular matrices of size *k xk*

Let $L_k,\Gamma_k$ be lower triangular matrices of size *k x k*

Let $\;\vec{l}, \;\vec{\gamma},\;\vec{u},\;\vec{v}\;$ be *k x 1* vectors and let $\;l,\;\gamma,\;u,\;v\;$ be real nonzero scalars, though not necessarily vector norms. 

\begin{align*}
  U_{K+1}V_{k+1} &\equiv 
  \underbrace{
    \begin{bmatrix} U_k & \vec{u} \\ \vec{0}^T & u\end{bmatrix}
  }_{U_{k+1}}
  \overbrace{
    \begin{bmatrix} V_k & \vec{v} \\ \vec{0}^T & v\end{bmatrix}
  }^{V_{k+1}}
  =\begin{bmatrix} U_kV_k & U_k\vec{v} + \vec{u}v \\ \vec{0}^T & uv
  \end{bmatrix}
  \\
  L_{k+1}\Gamma_{k+1}&\equiv
  \underbrace{
    \begin{bmatrix} K_k & \vec{0} \\ \vec{l}^T & l \end{bmatrix}
  }_{L_{k+1}}
  \overbrace{
    \begin{bmatrix} \Gamma_k & \vec{0} \\ \vec{\gamma}^T & \gamma
    \end{bmatrix}
  }^{\Gamma_{k+1}}
  =\begin{bmatrix} L_k\Gamma_k & \vec{0} \\ \vec{l}^T\Gamma_k + l\vec{\gamma}^T & l\gamma \end{bmatrix}
\end{align*}

We have that $u,v,l,\gamma$ must be nonzero for the *(k + 1) x (k + 1)* matrices to be upper or lower triangular. Because we assumed that the product $U_kV_k$ $(L_k\Gamma_k)$ to be upper (lower) triangular, this implies that the product $U_{k+1}V_{k+1}$ $(L_{k+1}\Gamma_{k+1})$ to be upper (lower) triangular 

i.e. $P(k)\implies P(k+1)$ for arbitrary positive integer $k.$ 

Because the base case is true, this means that our proposition $P(n)$ is true for all positive integers $n\geq2$. $\quad\quad\quad\quad\square$

---

Problem 7

---

In [0]:
A=np.array([[1,2,3],[2,3,17],[7,7,2]])
(n,m)=A.shape
L=np.zeros((n,n))
U=np.zeros((n,n))

**Doolittle algorithm, row version**

In [1091]:
L=np.zeros((n,n))
U=np.zeros((n,n))

for k in range(n):
  L[k][k] = 1.0
  for j in range(k):
    sum=0.0
    for s in range(k):
      sum = sum + L[k][s]*U[s][j]
    L[k][j] = (A[k][j] - sum)/U[j][j]
  for i in range(k,n):
    sum=0.0
    for s in range(k):
      sum = sum + L[k][s]*U[s][i]
    U[k][i]=(A[k][i]-sum)

print("A");print(A,end='\n\n');
print("L");print(L,end='\n\n');
print("U");print(U,end='\n\n');
print("A=LU");print(np.matmul(L,U),end='\n\n')

A
[[ 1  2  3]
 [ 2  3 17]
 [ 7  7  2]]

L
[[1. 0. 0.]
 [2. 1. 0.]
 [7. 7. 1.]]

U
[[  1.   2.   3.]
 [  0.  -1.  11.]
 [  0.   0. -96.]]

A=LU
[[ 1.  2.  3.]
 [ 2.  3. 17.]
 [ 7.  7.  2.]]



**Doolittle algorithm, column version**

In [1092]:
L=np.zeros((n,n))
U=np.zeros((n,n))

for k in range(n):
  L[k][k] = 1.0
  for j in range(k+1):
    sum=0.0
    for s in range (k):
      sum = sum + U[s][k]*L[j][s]
    U[j][k] = A[j][k] - sum
  for i in range(k+1,n):
    sum=0.0
    for s in range(k):
      sum = sum + L[i][s]*U[s][k]
    L[i][k]=(A[i][k]-sum)/U[k][k]

print("A");print(A,end='\n\n');
print("L");print(L,end='\n\n');
print("U");print(U,end='\n\n');
print("A=LU");print(np.matmul(L,U),end='\n\n')

A
[[ 1  2  3]
 [ 2  3 17]
 [ 7  7  2]]

L
[[1. 0. 0.]
 [2. 1. 0.]
 [7. 7. 1.]]

U
[[  1.   2.   3.]
 [  0.  -1.  11.]
 [  0.   0. -96.]]

A=LU
[[ 1.  2.  3.]
 [ 2.  3. 17.]
 [ 7.  7.  2.]]



---

Problem 35

---

Some definitions

In [0]:
#-------------------------------------------------------------------------------
def doolittle(A):
  #Perform Doolittle factorization on a matrix A. Returns the tuple (L,U), 
  #where L is unit lower triangular and U is upper triangular

  (n,m)=A.shape;L=np.zeros((n,n));U=np.zeros((n,n))

  for k in range(n):
    L[k][k] = 1.0
    for j in range(k):

      sum=0.0
      for s in range(k-1):
        sum = sum + L[k][s]*U[s][j]

      L[k][j] = (A[k][j] - sum)/U[j][j]
    for i in range(k,n):

      sum=0.0
      for s in range(k):
        sum = sum + L[k][s]*U[s][i] 

      U[k][i]=(A[k][i]-sum)

  return(L,U)
#-------------------------------------------------------------------------------
def crout(A):
  #Perform Crout factorization on a Matrix A. Returns the tuple (L,U), 
  #where L is lower triangular and U is unit upper triangular

  (n,m)=A.shape;L=np.zeros((n,n));U=np.zeros((n,n))
  for k in range(n):
    U[k][k] = 1.0
    for j in range(k,n):
      
      sum=0.0
      for s in range(k):
        sum = sum + L[j][s]*U[s][k]

      L[j][k]=A[j][k] - sum 
    
    for j in range(k+1,n):

      sum=0.0
      for s in range(k):
        sum = sum + L[k][s]*U[s][j]

      U[k][j] = (A[k][j] - sum )/L[k][k]
  
  return(L,U)
#-------------------------------------------------------------------------------

def cholesky2(A):
  #Takes as input a matrix A and determins its factorization A=LDU, where L is
  #lower triangular, D is diagonal, and U=L^T. 

  if np.all(np.linalg.eigvals(A) > 0) and np.all(A.transpose()-A ==0) :
    print("Input matrix is symmetric and positive definite!")
  else:
    print('Input matrix is not positive definite or non-symmetric')
    print('Try again.')
    return []

  (n,m)=A.shape;L=np.zeros((n,n));

  for k in range(n):

    sum=0
    for s in range(k):
      sum = sum + L[k][s]**2
    L[k][k] = (A[k][k] - sum)**(1/2)

    for i in range(k+1,n):
      sum=0
      for s in range(k):
        sum = sum + L[i][k]*L[k][s]
      L[i][k] = (A[i][k]- sum)/L[k][k]

  return(L)
#-------------------------------------------------------------------------------
def cholesky(A):
  #Takes as input a matrix A and determins its factorization A=LDU, where L is
  #lower triangular, D is diagonal, and U=L^T. 
  #
  #Returns the tuple (L,D)

  if np.all(np.linalg.eigvals(A) > 0) and np.all(A.transpose()-A ==0) :
    print("Input matrix is symmetric and positive definite!")
  else:
    print('Input matrix is not positive definite or non-symmetric')
    print('Try again.')
    return []

  (n,m)=A.shape;L=np.zeros((n,n));D=np.zeros((n,n))

  for k in range(n):
    L[k][k] = 1
    sum=0
    for s in range(k):
      sum = sum + (L[k][s]**2)*D[s][s]
    D[k][k] = A[k][k] - sum

    for i in range(k+1,n):
      sum=0
      for s in range(k):
        sum = sum + L[i][s]*L[k][s]*D[k][k]
      L[i][k] = (A[i][k]- sum)/D[k][k]
  
  return (L,D)
#-------------------------------------------------------------------------------
#I grabbed the following function (slightly modified) from this link
#https://stackoverflow.com/questions/18915378/rounding-to-significant-figures-in-numpy
__logBase10of2 = 3.010299956639811952137388947244930267681898814621085413104274611e-1

def RoundToSigFigs_fp( x, sigfigs ):
    """
    Rounds the value(s) in x to the number of significant figures in sigfigs.
    Return value has the same type as x.

    Restrictions:
    sigfigs must be an integer type and store a positive value.
    x must be a real value.
    """
    if not ( type(sigfigs) is int or type(sigfigs) is long or
             isinstance(sigfigs, np.integer) ):
        raise TypeError( "RoundToSigFigs_fp: sigfigs must be an integer." )

    if sigfigs <= 0:
        raise ValueError( "RoundToSigFigs_fp: sigfigs must be positive." )

    xsgn = np.sign(x)
    absx = xsgn * x
    mantissa, binaryExponent = np.frexp( absx )

    decimalExponent = __logBase10of2 * binaryExponent
    omag = np.floor(decimalExponent)

    mantissa *= 10.0**(decimalExponent - omag)

    if np.all(mantissa < 1.0):
        mantissa *= 10.0
        omag -= 1.0

    return xsgn * np.around( mantissa, decimals=sigfigs - 1 ) * 10.0**omag

Set print options and initialize the matrix A, which is real and symmetric.

In [0]:
A=np.array([[136.01,90.860,0.0,0.0],[90.860,98.810,-67.590,0.0],[0.0,-67.590,132.01,46.260],[0.0,0.0,46.260,177.17]])

$(i) \quad A=LU$, where $L$ is unit lower triangular and $U$ is upper triangular (Doolittle)

---

In [1095]:
(L,U)=doolittle(A)
LU=(np.matmul(L,U))
print("A");print(RoundToSigFigs_fp(A,5),end='\n\n')
print("L");print(RoundToSigFigs_fp(L,5),end='\n\n')
print("U");print(RoundToSigFigs_fp(U,5),end='\n\n')
print("A=LU");print(RoundToSigFigs_fp(LU,5),end='\n\n\n')

A
[[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]

L
[[ 1.      0.      0.      0.    ]
 [ 0.668   1.      0.      0.    ]
 [ 0.     -1.7735  1.      0.    ]
 [ 0.      0.      3.8099  1.    ]]

U
[[136.01    90.86     0.       0.    ]
 [  0.      38.112  -67.59     0.    ]
 [  0.       0.      12.142   46.26  ]
 [  0.       0.       0.       0.9222]]

A=LU
[[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]




$(ii)/(iv) \quad A=LDU=L^*{L^*}^{T}$, where $L$ and $L^*$ are unit lower triangular, $U$ is unit upper triangular, and $D$ is diagonal.

---

In [1096]:
(L,D)=cholesky(A)
U=np.transpose(L)
LDU=np.matmul(np.matmul(L,D),U)
print("A");print(RoundToSigFigs_fp(A,5),end='\n\n')
print("L");print(RoundToSigFigs_fp(L,5),end='\n\n')
print("D");print(RoundToSigFigs_fp(D,5),end='\n\n')
print("A=LDL^T");print(RoundToSigFigs_fp(LDU,5),end='\n\n\n')

Input matrix is symmetric and positive definite!
A
[[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]

L
[[ 1.      0.      0.      0.    ]
 [ 0.668   1.      0.      0.    ]
 [ 0.     -1.7735  1.      0.    ]
 [ 0.      0.      3.8099  1.    ]]

D
[[136.01     0.       0.       0.    ]
 [  0.      38.112    0.       0.    ]
 [  0.       0.      12.142    0.    ]
 [  0.       0.       0.       0.9222]]

A=LDL^T
[[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]




We can take the square root of $D$ element-wise to obtain $D^{1/2} = \big(\sqrt{d_{ii}}\big)$. $D$ and $D^{1/2}$ are diagonal. Then,


$$
A=LDL^T = LD^{1/2}D^{1/2}L^T = (LD^{1/2})(LD^{1/2})^T=L^*{L^*}^T
$$


The above is possible by the fact that a diagonal matrix is its own transpose and preserves the shape of other matrices under matrix multiplication. Thus, $L^*$ is also lower triangular.

$(iii)\quad A=LU $, where $L$ is lower triangular and $U$ is unit upper triangular (Crout)

---

In [1097]:
(L,U)=crout(A)
LU=np.matmul(L,U)
print("A");print(RoundToSigFigs_fp(A,5),end='\n\n')
print("L");print(RoundToSigFigs_fp(L,5),end='\n\n')
print("U");print(RoundToSigFigs_fp(U,5),end='\n\n')
print("A=LU");print(RoundToSigFigs_fp(LU,5),end='\n\n')

A
[[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]

L
[[136.01     0.       0.       0.    ]
 [ 90.86    38.112    0.       0.    ]
 [  0.     -67.59    12.142    0.    ]
 [  0.       0.      46.26     0.9222]]

U
[[ 1.      0.668   0.      0.    ]
 [ 0.      1.     -1.7735  0.    ]
 [ 0.      0.      1.      3.8099]
 [ 0.      0.      0.      1.    ]]

A=LU
[[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]



---
---
Section 4.3

---
---

Problem 1(b)

---

We want to solve the matrix equation 
$$
\begin{bmatrix}
  1 & 6 & 0 \\
  2 & 1 & 0 \\
  0 & 2 & 1 \\
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}
=
\begin{bmatrix} 3 \\ 1 \\  1 \end{bmatrix}
$$

**Gaussian Elimination**

\begin{align*}
\\
  A:
  \begin{bmatrix}
    1 & 6 & 0 \\
    2 & 1 & 0 \\
    0 & 2 & 1 \\
  \end{bmatrix}&
  &\begin{bmatrix}
    1 & 6 & 0 \\ (2) & -11 & 0 \\ 0 & 2 & 1
  \end{bmatrix}&
  &\begin{bmatrix}
    1 & 6 & 0 \\ (2) & -11 & 0 \\ 0 & (-2/11) & 1
  \end{bmatrix}
  \\   
  &\xrightarrow{R_2\equiv R_2-2R_1}&
  &\xrightarrow{R_3\equiv R_3 + \frac{2}{11}R_2}&
  \\
  x:
  \begin{bmatrix} 3 \\ 1 \\ 1 \end{bmatrix}&&
  \begin{bmatrix} 3 \\ -5 \\ 1 \end{bmatrix}&&
  \begin{bmatrix} 3 \\ -5 \\ 1/11 \end{bmatrix}
  \\\\
\end{align*}


Now, we can equivalently solve

$$
  \begin{bmatrix}
    1 & 6 & 0 \\ 0 & -11 & 0 \\ 0 & 0 & 1
  \end{bmatrix}
  \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}
  =
  \begin{bmatrix} 3 \\ -5 \\ 1/11 \end{bmatrix}
$$

$$ 
\boxed{x_2 = \frac{5}{11}}\quad \boxed{x_3=\frac{1}{11}} 
\\
x_1 + 6x_2 = x_1 + \frac{30}{11} = 3 \implies \boxed{x_1 = \frac{3}{11}}
$$
And we can rewrite A as

$$ A= LU = 
\begin{bmatrix} 
1 & 0 & 0 \\ 2 & 1 & 0 \\ 0 & -2/11 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 6 & 0 \\ 0 & -11 & 0 \\ 0 & 0 & 1
\end{bmatrix}
$$

We can check that this is correct


In [1098]:
A=np.array([[1,6,0],[2,1,0],[0,2,1]])
x=np.array([3/11,5/11,1/11]);x=np.transpose(x)
L=np.array([[1,0,0],[2,1,0],[0,-2/11,1]])
U=np.array([[1,6,0],[0,-11,0],[0,0,1]])
print('Ax = the vector: ',np.matmul(A,x),end='\n\n')
print('LU = the matrix: ')
print(np.matmul(L,U))

Ax = the vector:  [3. 1. 1.]

LU = the matrix: 
[[1. 6. 0.]
 [2. 1. 0.]
 [0. 2. 1.]]


**Scaled Row Pivoting**

Let $s$ define the vector whose elements $s_i$ are the elements in the $i^{th}$ row of A with the largest absolute value. Given the same $A$ as above, we see that 
$$ s = \begin{bmatrix} 6 \\ 2 \\ 2 \end{bmatrix} $$
We can determine the pivots of each row by comparing the diagonal entries of $A$ normalized by their respective $s_i$. 

$$ \frac{a_{11}}{s_1} = \frac{1}{6} \quad\quad \boxed{\frac{a_{22}}{s_2} = \frac{1}{2} \quad\quad \frac{a_{33}}{s_3} = \frac{1}{2}}$$

So, we can just choose the second row. We will first permute our matrix A by interchanging rows $R_1$ and $R_2$.

$$ 
\underbrace{
\begin{bmatrix}
  0 & 1 & 0 \\
  1 & 0 & 0 \\
  0 & 0 & 1
\end{bmatrix}}_{P = (R_1 \leftrightarrow R_2)}
\overbrace{
\begin{bmatrix} 
  1 & 6 & 0 \\
  2 & 1 & 0 \\
  0 & 2 & 1 
\end{bmatrix}}^A
=
\begin{bmatrix}
  2 & 1 & 0 \\
  1 & 6 & 0 \\
  0 & 2 & 1
\end{bmatrix}
$$

Get make the entries below our pivot $0$.

$$
\begin{bmatrix}
  2 & 1 & 0 \\
  1 & 6 & 0 \\
  0 & 2 & 1
\end{bmatrix}
\xrightarrow{R_2\equiv R_2 - \frac{1}{2} R_1}
\begin{bmatrix} 
  2 & 1 & 0 \\
  (1/2) & 11/2 & 0 \\
  0 & 2 & 1
\end{bmatrix}
$$
We will proceed with the same process as before. 

$$ 
\boxed{\frac{2_{11}}{2} = 1 \quad\quad \frac{{11/2}_{22}}{11/2} = 1}\quad\quad \frac{1_{33}}{2} = \frac{1}{2}
$$

We can just choose $R_1$. 

$$
\begin{bmatrix}
  2 & 1 & 0 \\
  (1/2) & 11/2 & 0 \\
  0 & 2 & 1
\end{bmatrix}
\xrightarrow{R_3 \equiv R_3 - \frac{4}{11} R_2}
\begin{bmatrix}
  2 & 1 & 0 \\
  (1/2) & 11/2 & 0 \\
  0 & (4/11) & 1
\end{bmatrix}
$$

We can construct the matrices $P,L,$ and $U$

\begin{align*}
PA&=LU \\
\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix}
\begin{bmatrix} 1 & 6 & 0 \\ 2 & 1 & 0 \\ 0 & 2 & 1 \end{bmatrix}
&=
\begin{bmatrix} 1 & 0 & 0 \\ 1/2 & 1 & 0 \\ 0 & 4/11 & 1\end{bmatrix}
\begin{bmatrix} 2 & 1 & 0 \\ 0 & 11/2 & 0 \\ 0 & 0 & 1 \end{bmatrix}
\end{align*}

We started with the equation $Ax=b$. It follows that $PAx=Pb$, but we know that $PA = LU$. We can now solve the equation

$$ LUx = Pb $$

in two steps. First, we can define $Ux\equiv z$ and solve $Lz = Pb$. We will then solve $Ux=z$ to obtain our final solution for $x$.



In [1099]:
A=np.array([[1,6,0],[2,1,0],[0,2,1]])
L=np.array([[1,0,0],[1/2,1,0],[0,4/11,1]])
U=np.array([[2,1,0],[0,11/2,0],[0,0,1]])
b=np.array([1,3,1]);b =np.transpose(b)

z = np.linalg.solve(L,b)
x = np.linalg.solve(U,z)

print('Vector x*11: ',x*11)

Vector x*11:  [3. 5. 1.]


And we see that our solution is the same as before
$$\boxed{ x_1 = 3/11 \quad\quad x_2 = 5/11 \quad\quad x_3 = 1/11}$$


---

Assume that A is an *n x n* banded real matrix with a bandwidth of *2k + 1* $(i.e. A_{ij}=0\text{ when } |i-j| > k)$. Show that the matrices $L$ and $U$ given by the Guassian elimination method (without pivoting) are also banded matrices with a bandwidth of *2k + 1*.

---

*Suppose* we have the matrix

$$
A = 
\begin{bmatrix}
  a_{11} & a_{12}  & \cdots  &a_{1,k+1} &  &  &&  \\
  a_{21} & a_{22}  & \ddots &\cdots & a_{2,k+2} &  &  &  \\
  \vdots & \ddots & \ddots &\ddots &\ddots&\ddots&&\\
  a_{k+1,1} &\ddots & \ddots& \ddots &\ddots&\ddots & \ddots \\ 
   & a_{k+2,2} &\ddots &\ddots & \ddots & \ddots & \ddots & a_{n-k,n} \\
   &  & \ddots & \ddots & \ddots & \ddots & \ddots & \vdots \\
   &  &  & \ddots & \ddots & \ddots & \ddots & \vdots \\
   &  &  &  & a_{n,n-k} & \cdots & \cdots & a_{nn}
\end{bmatrix}
$$

where the blanks are all 0. We perform gaussian elimination by eliminating the elements in the columns below the diagonal from left to right. That is, from column $C_1$ to column $C_{n-1}$. In each column, we eliminate its elements from top to bottom, starting with those in row $R_1$  and ending with those in row $R_{k+1}$. 

Taking from $R_i$ a multiple of a row $R_j$ has the restriction $ 1 \leq j \lt i$. The corresponding element $(l_{ij})$ will be located to the left of the diagonal entry. Moving on to the second column, we repeat the procedure. This time, subtracting a row $R_i$ by a multiple of some row $R_j$ has the restriction that $2 \leq j \lt  i$. The corresponding element  $(l_{ij})$ will again be to the left of the diagonal, but will also be to the right of the first element in the row $R_i$. This left-most element will be zero due to the procedure of Gaussian elimination that was carried out on the first column $C_1$. 

We want to avoid introducing nonzero entries into a column that we have eliminated. Therefore, when we are dealing with the elements in $C_i$, we only add multiple of rows $R_j$ such that $j \geq i$. For those in $C_3$, we avoid subtracting by $R_1$ or $R_2$, etc. This will ensure that we obtain a matrix that is indeed upper triangular.

The lower triangular matrix $L$ will also have at most bandwidth *2k + 1*. The elements of $L$ correspond to the multiples of rows that are added in the Gaussian elimination process. Adding a multiple of $R_j$ to $R_i$ will result in a nonzero element $(l_{ij})$. Because of our restriction, the elements that are already zero in the lower triangle will remain zero and the nonzero elements $(l_{ij})$ will be within this bandwidth.

The upper triangular matrix $U$ will also have at most bandwidth *2k + 1*. Entries will only be affected by those in rows higher than them. All elements that are 0 are either in $R_1$, which we leave alone, or have only zeros above them and are therefore unaffected by Gaussian elimination. 



---
---

Section 4.4

---
---

Problem 4 

---

**Show that for any two functions into** $\rm I \!R$

$$sup[f(x) + g(x)] \leq sup \{f(x)\} + sup \{g(x)\} $$


Let's begin with

\begin{gather} 
f(x) \leq sup\{f(x)\} \quad\quad g(x) \leq sup\{g(x)\} 
\\
f(x) + g(x) \leq sup\{f(x) + g(x)\}
\\\\
\end{gather}

So, f(x) + g(x) has a upper bound, which implies the existence of $sup\{f(x) + g(x)\}$. By the definition of supremum, $\forall \epsilon\in \rm I \!R\text{ s.t.}, \epsilon \gt 0,\quad\quad \exists \;x_f,x_g \in X \quad s.t$

\begin{gather}
   \big(sup\{f(x)\} - \epsilon\big) \lt f(x_f) \;,\; \big(sup\{g(x)\} - \epsilon \big) \lt g(x_g)
\end{gather}

which gives us

\begin{gather}
  sup\{f(x)\} + sup\{g(x)\} - 2\epsilon \lt f(x_f) + g(x_f)
  \\
\end{gather}

Therefore, the quantity $$sup\{f(x)\} + sup\{g(x)\}$$ is the supremum of $$f(x) + g(x)$$ In other words, 
$$
sup\{f(x)\} + sup\{g(x)\} = sup\{ f(x) + g(x)\} \quad\quad\square
$$

---

Problem 5

---

Disprove: $\lvert\lvert AB\rvert\rvert_\infty = \lvert\lvert A\lvert\lvert_\infty\lvert\lvert B\lvert\lvert_\infty$

\begin{align*}
  \lvert\lvert AB\rvert\rvert_\infty &= sup\{ \lvert\lvert ABu\lvert\lvert_\infty : \lvert\lvert u\lvert\lvert_\infty=1\}
  \\
  &\leq sup\{ \lvert\lvert A \lvert\lvert_\infty \lvert\lvert Bu\lvert\lvert_\infty : \lvert\lvert u \lvert\lvert = 1\}
  \\
  &= \lvert\lvert A \lvert\lvert_\infty sup\{ \lvert\lvert Bu\lvert\lvert_\infty : \lvert\lvert u \lvert\lvert = 1\}
  \\\\
  \lvert\lvert AB\lvert\lvert_\infty &\leq \lvert\lvert A \lvert\lvert_\infty \lvert\lvert B\lvert\lvert_\infty
\end{align*}

See below for a counter example

In [1100]:
A=np.array([[1,0,0],[0,11,1],[0,0,27]])
B=np.array([[1,1,1],[1,1,1],[1,0,1]])
AB=np.matmul(A,B)
print('Norm of A: ',np.linalg.norm(A,np.inf))
print('Norm of B: ',np.linalg.norm(B,np.inf))
print('Norm of AB:',np.linalg.norm(AB,np.inf))

Norm of A:  27.0
Norm of B:  3.0
Norm of AB: 54.0


What about the case when $B=A$? This is still not necessarily true. If we have 
$$
A=\begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix},
A^2=\begin{bmatrix} 0&0&0\\0&0&0\\0&0&0\end{bmatrix}
$$ 
then we see that 
\begin{align*}
  \lvert\lvert A^2 \rvert\rvert_\infty &\neq \lvert\lvert A\rvert\rvert_\infty \lvert\lvert A \rvert\rvert_\infty
  \\
  0 &\neq 1
\end{align*}

as shown below.


In [1101]:
A=np.array([[0,0,0],[0,0,1],[0,0,0]])
AA=np.matmul(A,A)
print('Norm of A, squared: ',np.linalg.norm(A,np.inf)**2) #using l2 norm
print('Norm of A^2: ',np.linalg.norm(AA,np.inf))          #"..........."

Norm of A, squared:  1.0
Norm of A^2:  0.0


---

Problem 7 

---

**Determine whether these expressions define norms on** $\rm I \!R^n:$

***(a)***  $max\{\lvert x_2\rvert, \lvert x_3 \rvert, \ldots , \lvert x_n \rvert \}$

No. This tentative norm does not satisfy the property that $$\lvert\lvert x \rvert\rvert = 0 \iff x =0$$ The norm could be zero for any value of $x_1$.

***(b)*** $\sum\limits_{i=1}^{n} \lvert x_i \rvert  ^3$

No. $\lvert\lvert a x \rvert\rvert = \sum\limits_{i=1}^n \lvert a x_i \rvert ^3 = a^3 \sum\limits_{i=1}^n \lvert x_i \rvert ^3 = a^3 \lvert\lvert x \rvert\rvert$, which violates the property that 
$$ \lvert\lvert a x \rvert\rvert = \lvert a \rvert \lvert\lvert x \rvert\rvert$$
for some $a\in \rm I \!R$.

***(c)*** $\bigg\{ \sum\limits_{i=1}^n \lvert x_i \rvert ^{1/2} \bigg\}^2$

No, this norm isn't subadditive. It doesn't satisfy the property 

$$ 
\lvert\lvert x + y \rvert\rvert \leq \lvert\lvert x \rvert\rvert + \lvert\lvert y \rvert\rvert
$$
 A counterexample: 

In [1102]:
def normm(v):
  self = 0
  for i in range(len(v)):
    self = self + np.sqrt(abs(v[i]))
  self = self**2
  return self

x=np.array([1,0])
y=np.array([0,1])
z=x+y

print("Norm of 'x+y': ", normm(z))
print("Norm of x + norm of y: ", normm(x)+normm(y))

Norm of 'x+y':  4.0
Norm of x + norm of y:  2.0


***(d)*** $max\{\lvert x_1 - x_2 \rvert, \lvert x_1 + x_2 \rvert , \lvert x_3  \rvert, \ldots,\lvert x_n\rvert \}$

Yes. This norm is 0 $\iff$ all entries $x_i =0$. It is also homogeneous (degree 1):

\begin{align*}
  max\{\lvert ax_1 - ax_2 \rvert, \lvert ax_1 + ax_2 \rvert , \lvert ax_3  \rvert, \ldots,\lvert ax_n\rvert \} &= \lvert a \rvert max\{\lvert x_1 - x_2 \rvert, \lvert x_1 + x_2 \rvert , \lvert x_3  \rvert, \ldots,\lvert x_n\rvert \}
  \\
  \lvert\lvert a x \rvert\rvert &= \lvert a \rvert \lvert\lvert x \rvert\rvert
\end{align*}

This norm is also subadditive. 

\begin{align*}
  \lvert\lvert x + y \rvert\rvert &= max\{\lvert x_1 +y_1 - (x_2 +y_2) \rvert, \lvert x_1 + y_1 + x_2 + y_2 \rvert , \lvert x_3 + y_3 \rvert, \ldots,\lvert x_n + y_n\rvert \}
  \\
  &\leq max\{\lvert x_1 - x_2\rvert + \lvert y_2 - y_2\rvert, \lvert x_1 + x_2 \rvert + \lvert y_1 + y_2 \rvert, \lvert x_3 \rvert + \vert y_3 \rvert, \ldots,\lvert x_n\rvert + \vert y_n \rvert\}
  \\
  &\leq max\{ \lvert x_1 - x_2 \rvert, \lvert x_1 + x_2 \rvert, \lvert x_3 \rvert, \ldots, \lvert x_n \rvert \} + max\{ \lvert y_1 - y_2 \rvert, \lvert y_1 + y_2 \rvert, \lvert y_3 \rvert, \ldots \lvert y_n \rvert\}
  \\\\
  \lvert\lvert x + y \rvert\rvert &\leq
  \lvert\lvert x \rvert\rvert + \lvert\lvert y \rvert\rvert
\end{align*}

***(e)*** $\sum\limits_{i=1}^n 2^{-i} \lvert x_i\rvert$

Yes. This norm is 0 $\iff\, x_i = 0 \quad\forall i\in\{1,\ldots,n\}$. Additionally, it is homogeneous (degree 1):

\begin{align*}
  \sum\limits_{i=1}^n 2^{-i} \lvert a x_i\rvert &= \lvert a \rvert \sum\limits_{i=1}^n \lvert x_i\rvert
  \\\\
  \lvert\lvert a x \rvert\rvert &= \lvert a \rvert \lvert\lvert x \rvert\rvert
\end{align*}

This norm is also subadditive.

\begin{align*}
  \lvert\lvert x + y \rvert\rvert &= \sum\limits_{i=1}^n 2^{-i} \lvert x_i + y_i \rvert \leq \sum\limits_{i=1}^n 2^{-i} \bigg( \lvert x_i \rvert + \vert y_i \rvert \bigg) = \bigg(\sum\limits_{i=1}^n 2^{-i}\lvert x_i \rvert\bigg) + \bigg( \sum\limits_{i=1}^n 2^{-i}\lvert y_i \rvert\bigg)
  \\\\
  \lvert\lvert x + y \rvert\rvert & \leq \lvert\lvert x \rvert\rvert + \lvert\lvert y \rvert\rvert
\end{align*}